### ISSUE TITLE
Worlds won't load in 1.18.2 update

### ISSUE THREAD

**Issue by EGOIST1372** [Tfarcenim/FabricFastFurnace#13]
Hi
Worlds won't load
as you can see in screenshot even if I select safe mode it won't load world and there is no data pack active
![image](https://user-images.githubusercontent.com/86555131/158542230-ca38d7a1-a135-41c5-b16d-104c5ff3aaba.png)

**Comment by zax71** [comment]
Another byproduct of this is on servers, crafting breaks

**Comment by jmdev91** [comment]
Adding/removing Data Packs also seems to break in 1.18.2. Endless loop of failing to rebuild the fuel map, due to a mixin error (seems the common problem among all 1.18.1 mods that break in 1.18.2).

**Comment by EGOIST1372** [comment]
@Tfarcenim any news on 1.18.2 update?

**Comment by Tfarcenim** [comment]
done
