### ISSUE TITLE
Breaks when used on dedicated servers

### ISSUE THREAD

**Issue by calloatti** [Tfarcenim/FabricFastFurnace#2]
MC 1.16.1
fabric-api-0.15.0+build.379-1.16.1.jar
fastfurnace-2.1.jar

Dedicated server

Unable to shift click coal into furnace, and when dragging fuel into furnace it seems there is a client/server desync

https://www.youtube.com/watch?v=4QcjLGfy6tU

**Comment by Tfarcenim** [comment]
any logs from the server side?

**Comment by calloatti** [comment]
Nothing on the server console when doing what you see in the video

Edit: And nothing in latest.log after disconnecting and stopping the server.

**Comment by Tfarcenim** [comment]
I hate furnaces, should be fixed in a few minutes.

**Comment by Tfarcenim** [comment]
Ironic, this issue wouldn't have happened if the clients were vanilla, anyways, case closed.
