### ISSUE TITLE
Fabric API Dependency Unnecessary?

### ISSUE THREAD

**Issue by mrgrim** [Tfarcenim/FabricFastFurnace#3]
I was curious how this mod utilizes the Fabric API considering its dependency on it, but after reviewing the code I can't find any use of the Fabric API. All of the imports are from Mixin, Minecraft, or the mods own packages. The dependency seems to be a relic from the fabric example mod including the suggested "flamingo" mod.

Am I missing something, or can this dependency be removed? Right now this mod is the only reason I load the fabric API on my server at all!

**Comment by Tfarcenim** [comment]
Because I didn't want to take the chance that something needed the fabric api and end up with a crash report on my hands.

**Comment by mrgrim** [comment]
Unless a package from the API is imported and used explicitly, it won't be needed. The API is optional, meaning the Fabric loader can be used without it. Since the API adds overhead of its own, it shouldn't be listed as a dependency if it's not required. This is doubly true for optimization mods like this one.

**Comment by mrgrim** [comment]
What I can do is build a version without the dependency then run it on my server for a while. I can report back if we run into any problems. Would that help?

**Comment by Tfarcenim** [comment]
I'll upload a version without the fabric api and see if that explodes or not

**Comment by Tfarcenim** [comment]
gonna take it as a no
